POST http://localhost:3003/user/cadastro
Content-Type: application/json

{
	"nome": "Graziela",
	"email": "grazi@gra.com",
	"password": "123456",
	"role": "normal"
}

###
# @name login

POST http://localhost:3003/user/login
Content-Type: application/json

{
	"email": "beatriz@bia.com",
	"password": "123456"
}

###
@token = {{login.response.body.token}}
// perfil usuario

GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTFkNDBkLTNjNzMtNGJkNy05OGU4LWJkMDI0NDlhMWI4YiIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NTY2MTY5MjQsImV4cCI6MTY1NjYxNzUyNH0.LHsL6yOdyRz4XEd9CiA_4fTHBqeU-AJCHNMpWRFDsw4
 ###

// perfil de outro usuario

GET http://localhost:3003/user/:id
Content-Type: application/json
Authorization: {{token}}

###

# POST http://localhost:3003/receita
# Content-Type: application/json
# Authorization: {{token}}


# {
# 	"title": "Strogonoff de Carne",
# 	"description": "Creme de Leite,catchup delicia demais!!"
# }

# // Criar receita

# ###

# // Pegar Receita

# GET http://localhost:3003/receita:id
# Content-Type: application/json
# Authorization: {{token}}


# {
# 	"id": "id da receita",
# 	"title": "Strogonoff de Carne",
# 	"description": "Creme de Leite,catchup delicia demais!!"
# 	"cratedAt": "20/12/2020"
# }


