POST http://localhost:3003/signup
Content-Type: application/json

{
	"name": "graziela",
    "email": "grazi@gmail.com.br",
	"password": "543210"
}

###

# @name login
POST http://localhost:3003/login
Content-Type: application/json

{
	"email": "grazi@gmail.com.br",
	"password": "543210"
}

###

@token = {{login.response.body.token}}

POST http://localhost:3003/post
Content-Type: application/json
Authorization: {{token}}

{
	"photo": "foto4",
    "description": "descricao4",
	"type": "NORMAL"
}

###

GET http://localhost:3003/post/951ffb00-d1e6-4aef-b925-1a87f9280310
Content-Type: application/json
# Authorization: {{token}}




