POST http://localhost:3003/signup
Content-Type: application/json

{
	"name": "natalia",
    "email": "nathy@gmail.com.br",
	"password": "543210"
}

###

# @name login
POST http://localhost:3003/login
Content-Type: application/json

{
	"email": "nathy@gmail.com.br",
	"password": "543210"
}

###

@token = {{login.response.body.token}}

POST http://localhost:3003/post
Content-Type: application/json
Authorization: {{token}}

{
	"photo": "https://sm.ign.com/t/ign_br/screenshot/default/blue-bayou-in-cinema-character-banners-black-widow-brazil_kzgq.600.jpg",
    "description": "Viuva Negra",
	"type": "EVENT"
}

###

GET http://localhost:3003/post/85436df1-f6bd-4d9e-872a-4bf6ace970bb
Content-Type: application/json
Authorization: {{token}}




